### ISSUE TITLE
Failed to install FlashWeave

### ISSUE THREAD

**Issue by Lin936** [meringlab/FlashWeave.jl#13]
I am just starting to learn Julia. I would like to use FlashWeave to analyze my data, but failed to install FlashWeave. 
The error is : Unable to automatically install  "  OpenSpecFun" from C:\.julia\packages\OpenSpecFun_j11\G7uzt\Artifacts.tom1
How should I solve this error?
Thanks for your help

**Comment by jtackm** [comment]
Hi, sorry to hear that. I've never encountered this error on any of our test systems, but googling your error message suggest's that it's a problem unrelated to FlashWeave. Perhaps your curl installation (used to download packages) could be problematic: https://discourse.julialang.org/t/cant-install-openspecfun-jll/33593 . You can follow the lead of the person asking there and talk to your sysadmin to fix this.

You may also be hitting a BinaryBuilder.jl bug, so make sure you use the latest version of Julia (1.3.1, you see it by typing ```versioninfo()```) and BinaryBuilder: https://discourse.julialang.org/t/julia-v1-3-0-has-been-released/31549/19
https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/527

You may also consider asking directly in those places (in particular the first discourse link I provided) since people there have a better grasp on Julia package management issues. If it turns out to be FlashWeave-specific, please let me know and I'll see how I can make it work on my end.

**Comment by Lin936** [comment]
Thank you so much! 
I am trying to solve Julia problem.

**Comment by jtackm** [comment]
Closing this for now, we can re-open if the issue turns out to be in FlashWeave.
